
num1=2
num2=2



try:
    x=num1/num2
except:
    print("Erro en el programa")

finally:
    print("Programa de try")